export interface CharacterData {
  id: number;
  fullname: string | string[];
  nickname: string | string[];
  description: string | string[];
  likes: string[] | string[][];
  dislikes: string[];
  hobbies: string[];
  birthday_date: string; // MM-DD
  profile_picture: string | string[];
  image_color: string | string[];
}

export const Characters = [
  {
    id: 1,
    fullname: 'Kasumi Toyama',
    nickname: 'Kasumi',
    description:
      "Poppin'Party's forever positive and energetic guitarist and vocalist. Although she cares for her friends and brings fun and cheer wherever she is, she sometimes becomes too excited. Together with her dear friends, she enjoys each day as she charges on in search of all things sparkling and heart-pounding!",
    likes: ['French fries', 'White rice'],
    dislikes: ['Natto'],
    hobbies: [
      'Karaoke',
      'Going on adventures',
      'Trying new things',
      'Growing herbs with her sister',
    ],
    birthday_date: '07-14',
    profile_picture: '/images/characters/kasumi_profile.webp',
    image_color: '#FF5522',
  },
  {
    id: 2,
    fullname: 'Tae Hanazono',
    nickname: 'Tae',
    description:
      "A skilled guitarist who has been playing since elementary school. Hardly a day goes by when she isn't dedicating herself to music and the guitar as Poppin'Party's guitarist. She takes things at her own pace and is considerably airheaded, sometimes resulting in statements that baffle those around her.",
    likes: ['Hamburg steak', 'Sweet red bean soup', 'Anything edible'],
    dislikes: ['None (Nothing too weird, though...)'],
    hobbies: ['Running (no marathons)', 'Taking long baths', 'Working with clay'],
    birthday_date: '12-04',
    profile_picture: '/images/characters/tae_profile.webp',
    image_color: '#0077DD',
  },
  {
    id: 3,
    fullname: 'Rimi Ushigome',
    nickname: 'Rimi',
    description:
      "Poppin'Party's bassist. Though she appears unassuming, she is extremely passionate about music and has composed many of the band's songs. Whether it's music, studying, or even things she has difficulty with, she's always willing to do her best. Eating lots of things she enjoys is how she gets her energy.",
    likes: ['Yamabuki Bakery bread', 'Meat', 'Fresh cream', 'Chocolate (unless minty)'],
    dislikes: ['Mint chocolate'],
    hobbies: [
      'Playing video games',
      'Reading',
      'Collecting picture books',
      'Running a blog about comparing different sweets and pastries',
    ],
    birthday_date: '03-23',
    profile_picture: '/images/characters/rimi_profile.webp',
    image_color: '#FF55BB',
  },
  {
    id: 4,
    fullname: 'Saya Yamabuki',
    nickname: 'Saya',
    description:
      "Her family runs a popular downtown bakery called Yamabuki Bakery. She's reliable and supports the band both as a drummer and by providing emotional support. Her hobby is photography, and on her days off, she can sometimes be seen taking walks with a camera in her hand.",
    likes: ['Spaghetti aglio e olio', 'Spaghetti aglio, olio e peperoncino', 'Cheese'],
    dislikes: ['Raw seafood'],
    hobbies: ['Collecting hair accessories', 'Karaoke', 'Watching baseball', 'Photography'],
    birthday_date: '05-19',
    profile_picture: '/images/characters/saya_profile.webp',
    image_color: '#FFCC11',
  },
  {
    id: 5,
    fullname: 'Arisa Ichigaya',
    nickname: 'Arisa',
    description:
      "Arisa's grandparents run the pawn shop Ryuseido. She is very much an indoor girl who likes taking care of her bonsai trees and looking at stuff online. She does not go out much, but is incredibly smart and gets very good grades at school. Her sharp tongue causes her and Kasumi to butt heads quite a bit. She used to take piano lessons, but since quit.",
    likes: ['Anmitsu', 'Brown rice', 'Hard-boiled eggs', 'Chikuzenni'],
    dislikes: ['Leeks'],
    hobbies: ['Caring for bonsai trees', 'Surfing the Internet'],
    birthday_date: '10-27',
    profile_picture: '/images/characters/arisa_profile.webp',
    image_color: '#AA66DD',
  },
  {
    id: 6,
    fullname: 'Ran Mitake',
    nickname: 'Ran',
    description:
      "The only daughter of the head of a school of flower arrangement with over 100 years of history. She serves as Afterglow's guitarist and vocalist. Though seemingly aloof and unapproachable, in actuality, she is kind and cares deeply for her friends. She engages in both flower arrangement and band activities with tireless dedication.",
    likes: ['Dark chocolate sweets'],
    dislikes: ['Peas'],
    hobbies: ['None'],
    birthday_date: '04-10',
    profile_picture: '/images/characters/ran_profile.webp',
    image_color: '#EE0022',
  },
  {
    id: 7,
    fullname: 'Moca Aoba',
    nickname: 'Moca',
    description:
      "Afterglow's guitarist. She takes doing things at her own pace to a whole new level and becomes extremely absorbed in the things that do interest her. Behind her jokes and airy demeanor is a person capable of great passion. Her love of bread knows no bounds, and she is especially fond of the bread from Yamabuki Bakery.",
    likes: ['Buns'],
    dislikes: ['Anything spicy'],
    hobbies: ['Sleeping', 'Collecting point cards'],
    birthday_date: '09-03',
    profile_picture: '/images/characters/moca_profile.webp',
    image_color: '#00CCAA',
  },
  {
    id: 8,
    fullname: 'Himari Uehara',
    nickname: 'Himari',
    description:
      "Afterglow's cheerful and energetic leader and bassist brightens the mood wherever she goes. She loves fashion and chatting, and her friendliness allows her to easily befriend people she meets for the first time. Between band, work, hobbies, and occasionally studying, she lives her life to the fullest.",
    likes: ['Chocolate', 'Convenience store snacks'],
    dislikes: ['Shiitake mushrooms', 'Spicy things (especially snacks)'],
    hobbies: [
      'Comparing sweets from different convenience stores',
      'Baking',
      'Reading fashion magazines',
    ],
    birthday_date: '10-23',
    profile_picture: '/images/characters/himari_profile.webp',
    image_color: '#FF9999',
  },
  {
    id: 9,
    fullname: 'Tomoe Udagawa',
    nickname: 'Tomoe',
    description:
      "Afterglow's drummer. Naturally candid and good-natured, she has the trust of the adults downtown. While normally a dependable source of support for the band, she sometimes lets her straightforwardness get the better of her or plays pranks out of mischievousness.",
    likes: ['Pork bone and soy sauce ramen'],
    dislikes: ['None'],
    hobbies: ['Fashion', 'Taiko drumming'],
    birthday_date: '04-15',
    profile_picture: '/images/characters/tomoe_profile.webp',
    image_color: '#BB0033',
  },
  {
    id: 10,
    fullname: 'Tsugumi Hazawa',
    nickname: 'Tsugumi',
    description:
      "Afterglow's keyboardist is the one who manages to bring together the group of colorful childhood friends. She doesn't recognize that she has the inner strength to follow through with anything and the energy to act on her decisions. Being quick to act as well, when something catches her eye, she'll often get the others involved.",
    likes: ["Her mother's cakes"],
    dislikes: ['Black coffee'],
    hobbies: ['Collecting bath powder'],
    birthday_date: '01-07',
    profile_picture: '/images/characters/tsugumi_profile.webp',
    image_color: '#FFEE88',
  },
  {
    id: 11,
    fullname: 'Kokoro Tsurumaki',
    nickname: 'Kokoro',
    description:
      "A free-spirited and natural-born entertainer who isn't bound by convention. She loves smiles, and her actions are motivated by the desire to make the world smile. Just like her, Hello, Happy World! continues to expand its activities to include things that typically fall outside of what a band would normally do.",
    likes: ['Everything'],
    dislikes: ['None'],
    hobbies: ['Looking for fun things to do'],
    birthday_date: '08-08',
    profile_picture: '/images/characters/kokoro_profile.webp',
    image_color: '#FFEE22',
  },
  {
    id: 12,
    fullname: 'Kaoru Seta',
    nickname: 'Kaoru',
    description:
      "A popular girl in her school's drama club, Kaoru is constantly surrounded by fans. She enjoys reading poetry and books and philosophy, but does not necessarily understand a word that they say.",
    likes: [['Grape juice', 'Sachertorte', 'Vichyssoise'], ['Miso soup']],
    dislikes: ['Raw seafood'],
    hobbies: ['Reading philosophy books'],
    birthday_date: '02-28',
    profile_picture: '/images/characters/kaoru_profile.webp',
    image_color: '#AA33CC',
  },
  {
    id: 13,
    fullname: 'Hagumi Kitazawa',
    nickname: 'Hagumi',
    description:
      "Hello, Happy World!'s animated and expressive bassist. She is also the daughter of a butcher famous for its croquettes and can often be seen manning the store. During critical moments, such as when the softball team she captains has a game, she can be quite dependable as well.",
    likes: ["Croquettes from her family's shop", 'Meat', 'Curry'],
    dislikes: ['None'],
    hobbies: ['Running marathons'],
    birthday_date: '07-30',
    profile_picture: '/images/characters/hagumi_profile.webp',
    image_color: '#FF9922',
  },
  {
    id: 14,
    fullname: 'Kanon Matsubara',
    nickname: 'Kanon',
    description:
      "Once shy and hesitant, she has found courage thanks to the experience of making many people smile through her band's unconventional activities. While she has become somewhat more assertive, she still has trouble saying no and gets easily lost.",
    likes: ['Sweets', 'Cake', 'Coffee', 'Black tea'],
    dislikes: ['Mushrooms'],
    hobbies: ['Watching jellyfish', 'Cafe-hopping'],
    birthday_date: '05-11',
    profile_picture: '/images/characters/kanon_profile.webp',
    image_color: '#44DDFF',
  },
  {
    id: 15,
    fullname: ['Misaki Okusawa', 'Michelle'],
    nickname: ['Misaki', 'Michelle'],
    description: [
      "Joined Hello, Happy World while working part-time as a mascot. Aside from Kanon, no one knows the true identity of Michelle. As she's reluctant to work hard, she is the type that does everything in moderation.",
      'The DJ for Hello, Happy World! It seems that she was scouted during her part-time job...?!',
    ],
    likes: ["Anything on a family restaurant's menu"],
    dislikes: ['Cilantro'],
    hobbies: ['Making felt dolls for her little sister'],
    birthday_date: '10-01',
    profile_picture: [
      '/images/characters/misaki_profile.webp',
      '/images/characters/michelle_profile.webp',
    ],
    image_color: ['#006699', '#DD33CC'],
  },
  {
    id: 16,
    fullname: 'Aya Maruyama',
    nickname: 'Aya',
    description:
      "Pastel＊Palettes's vocalist is an idol who loves idols more than anyone. Her ability to remain positive and never give up continues to influence the other members. The kindness she shows the agency's newer idols makes her someone they come to, but her tendency to stumble over words remains.",
    likes: ['Omurice', 'Hamburg steak'],
    dislikes: ['Octopus'],
    hobbies: ['Social media', 'Taking selfies'],
    birthday_date: '12-27',
    profile_picture: '/images/characters/aya_profile.webp',
    image_color: '#FF88BB',
  },
  {
    id: 17,
    fullname: 'Hina Hikawa',
    nickname: 'Hina',
    description:
      "Pastel＊Palettes's guitarist and an actual genius. She loves fun things that make her feel boppin'♪ Although there have been times when her bluntness has almost caused trouble, she does care about the band. She dreams of someday standing on the same stage as her older sister Sayo.",
    likes: ['Junk food (especially gum and candy)'],
    dislikes: ['Tofu (especially tofu skins)', 'Food with little taste'],
    hobbies: ['Making aroma oils'],
    birthday_date: '03-20',
    profile_picture: '/images/characters/hina_profile.webp',
    image_color: '#55DDEE',
  },
  {
    id: 18,
    fullname: 'Chisato Shirasagi',
    nickname: 'Chisato',
    description:
      'An idol and actress who has been acting since childhood. Her calm and pragmatic personality can make her seem cold, but her attitude is simply a sign of her uncompromising professionalism. She is currently growing both as an actress and an idol as a result of the stimulating new experiences of college life.',
    likes: ['Black tea', 'Açaí na tigela', 'Food with a refreshing taste'],
    dislikes: ['Natto'],
    hobbies: ['Shopping', 'Visting cafes'],
    birthday_date: '04-06',
    profile_picture: '/images/characters/chisato_profile.webp',
    image_color: '#FFEEAA',
  },
  {
    id: 19,
    fullname: 'Maya Yamato',
    nickname: 'Maya',
    description:
      "Pastel＊Palettes's drummer went from being a studio musician to an idol. A hopeless geek when it comes to music equipment, she sometimes even writes magazine articles on the subject. Inspired by the agency's newer idols and a drummer she respects deeply, she continues to be an idol who remains true to who she is.",
    likes: ['Vegetable sticks'],
    dislikes: ['Haute cuisine'],
    hobbies: ['Tinkering with sound equipment'],
    birthday_date: '11-03',
    profile_picture: '/images/characters/maya_profile.webp',
    image_color: '#99DD88',
  },
  {
    id: 20,
    fullname: 'Eve Wakamiya',
    nickname: 'Eve',
    description:
      "Pastel＊Palettes's keyboardist is a former model born to a Japanese father and a Finnish mother. She follows bushido but sometimes loses sight of her surroundings. However, her single-minded dedication has also helped the other members countless times.",
    likes: ['Gingerbread cookies'],
    dislikes: ['Nukazuke'],
    hobbies: ['Watching period dramas', 'Collecting pennants'],
    birthday_date: '06-27',
    profile_picture: '/images/characters/eve_profile.webp',
    image_color: '#DDBBFF',
  },
  {
    id: 21,
    fullname: 'Yukina Minato',
    nickname: 'Yukina',
    description:
      "Roselia's cool and dignified songstress. She retains the purity of her passion for music even while immersing herself even more deeply in music since becoming a professional musician. Somewhat of a klutz when it comes to non-musical matters, she manages with the help of the other members. She and Lisa are childhood friends.",
    likes: ['Honey tea', 'Cookies made by Lisa', 'Stew'],
    dislikes: ['Anything too bitter (especially bitter melon)'],
    hobbies: ['None'],
    birthday_date: '10-26',
    profile_picture: '/images/characters/yukina_profile.webp',
    image_color: '#881188',
  },
  {
    id: 22,
    fullname: 'Sayo Hikawa',
    nickname: 'Sayo',
    description:
      "A calm and serious individual who is strict toward others and herself. She continues honing her sound as Roselia's guitarist in the hopes that she will someday join her younger sister Hina on the same stage. Whether it is music, gaming, or baking, she is always uncompromising.",
    likes: ['Junk food (especially gum and candy)'],
    dislikes: ['Carrots'],
    hobbies: ['None'],
    birthday_date: '03-20',
    profile_picture: '/images/characters/sayo_profile.webp',
    image_color: '#00AABB',
  },
  {
    id: 23,
    fullname: 'Lisa Imai',
    nickname: 'Lisa',
    description:
      "Roselia's compassionate bassist brightens the mood for the band with her innate cheerfulness. She is also very attentive and takes good care of others. With a large social circle, she is also close with many members of the other bands. She and Yukina are childhood friends.",
    likes: ['Chikuzenni', 'Sour foods', 'Boiled foods'],
    dislikes: ['Green smoothies'],
    hobbies: ['Knitting', 'Shopping', 'Baking cookies'],
    birthday_date: '08-25',
    profile_picture: '/images/characters/lisa_profile.webp',
    image_color: '#DD2200',
  },
  {
    id: 24,
    fullname: 'Ako Udagawa',
    nickname: 'Ako',
    description:
      "Guided by her own version of cool, Roselia's drummer charges fearlessly ahead. She may be the cheerful and friendly little sister figure of the band, but her intimate knowledge of what makes Roselia cool allows her to guide the band at times. Even now, she continues to try to find ways to say cool things.",
    likes: ['Potato chips', 'Jelly beans'],
    dislikes: ['Sea cucumbers', 'Eggs', 'Bell peppers', 'Broccoli'],
    hobbies: ['Finding the latest and coolest trends'],
    birthday_date: '07-03',
    profile_picture: '/images/characters/ako_profile.webp',
    image_color: '#DD0088',
  },
  {
    id: 25,
    fullname: 'Rinko Shirokane',
    nickname: 'Rinko',
    description:
      "Roselia's keyboardist. Though timid and reserved, she is thoughtful and quite resolute deep down. Her courage and strength when it comes to facing what she finds difficult is highly regarded by those around her. She also becomes utterly engrossed when it comes to what she enjoys, such as gaming and designing outfits.",
    likes: ['Hot milk'],
    dislikes: ['Celery'],
    hobbies: ['Playing online games', 'Solving crosswords', 'Reading'],
    birthday_date: '10-17',
    profile_picture: '/images/characters/rinko_profile.webp',
    image_color: '#BBBBBB',
  },
  {
    id: 26,
    fullname: 'Mashiro Kurata',
    nickname: 'Mashiro',
    description:
      'A meek and mature young girl. She managed to get into her dream school Tsukinomori but felt discouraged after seeing the talented student body. However, since joining her band, her outlook has begun to change. She is the lyricist for the band and possesses a very active imagination. This does cause her to daydream frequently, though.',
    likes: ['Beef stew'],
    dislikes: ['Spinach', 'Peas', 'Carrots', 'Pickles', 'Most foods disliked by children'],
    hobbies: ['Knitting', 'Collecting stuffed animals'],
    birthday_date: '02-19',
    profile_picture: '/images/characters/mashiro_profile.webp',
    image_color: '#6677CC',
  },
  {
    id: 27,
    fullname: 'Toko Kirigaya',
    nickname: 'Toko',
    description:
      "A positive high school girl who is always sunny. She doesn't sweat the details and is popular both at school and on social media. Although she has always had difficulty committing to any one thing for long, she finds her interest and attachment toward the band growing.",
    likes: ['Instant fried noodles'],
    dislikes: ['Mint gum'],
    hobbies: ['Using social media', 'Designing clothes'],
    birthday_date: '12-16',
    profile_picture: '/images/characters/toko_profile.webp',
    image_color: '#EE6666',
  },
  {
    id: 28,
    fullname: 'Nanami Hiromachi',
    nickname: 'Nanami',
    description:
      'An extremely gifted girl who is talented at many things, especially the arts. Her past experiences have caused her to conceal her gift, but since joining Morfonica, she finds herself becoming more willing to show who she really is. She is currently living the fun high school life she has always dreamed of.',
    likes: ['Spicy food', 'Unique foods'],
    dislikes: ['None'],
    hobbies: ['Collecting toys and prizes that come with products'],
    birthday_date: '06-16',
    profile_picture: '/images/characters/nanami_profile.webp',
    image_color: '#EE7744',
  },
  {
    id: 29,
    fullname: 'Tsukushi Futaba',
    nickname: 'Tsukushi',
    description:
      "Morfonica's confident leader. She used to try to do things that were beyond her and often failed as a result, but she has learned to focus on what she can do. She's trying to become someone who can shine with pride.",
    likes: ["Her mother's curry", 'Donuts'],
    dislikes: ['Green vegetables'],
    hobbies: ['Hairstyling'],
    birthday_date: '09-15',
    profile_picture: '/images/characters/tsukushi_profile.webp',
    image_color: '#EE7788',
  },
  {
    id: 30,
    fullname: 'Rui Yashio',
    nickname: 'Rui',
    description:
      'An intelligent girl whose grades have kept her at the top of her class. She has a dry personality and aims to always be the best. She once quit violin after judging it as meaningless. However, she has since returned to the world of music after meeting Mashiro and the others. She is in charge of composing music for the band.',
    likes: ['Zenzai soup with mochi'],
    dislikes: ['Rich foods', 'Foods with strong flavors'],
    hobbies: ['None'],
    birthday_date: '11-19',
    profile_picture: '/images/characters/rui_profile.webp',
    image_color: '#669988',
  },
  {
    id: 31,
    fullname: 'Rei Wakana',
    nickname: ['LAYER', 'Rei'],
    description:
      "RAISE A SUILEN's vocalist seems calm and mature, but she can also be quite passionate and has the adorable cuteness of someone her age. She has loved singing ever since she was little, and her skills as a bassist make her popular as a support musician. She and Tae Hanazono are childhood friends.",
    likes: ['Hot milk (with honey)'],
    dislikes: ['Bitter coffee', 'Sea cucumbers'],
    hobbies: ['Stretching'],
    birthday_date: '01-13',
    profile_picture: '/images/characters/layer_profile.webp',
    image_color: '#CC0000',
  },
  {
    id: 32,
    fullname: 'Rokka Asahi',
    nickname: ['LOCK', 'Roka'],
    description:
      "Always does her best. She came to Tokyo because of how much she loves Poppin'Party. Her relatives operate Asahi Bathhouse, and she lives and works there while serving as RAISE A SUILEN's guitarist. Her passion when it comes to guitar is second to none. Hailing from Gifu Prefecture, her dialect sometimes slips out.",
    likes: ['Anko', 'Roasted sweet potatoes', 'Apple pie'],
    dislikes: [
      'Eating ramen in public (she eats slowly, so others get impatient and cause her to be anxious)',
    ],
    hobbies: ['Playing guitar'],
    birthday_date: '07-17',
    profile_picture: '/images/characters/lock_profile.webp',
    image_color: '#AAEE22',
  },
  {
    id: 33,
    fullname: 'Masuki Sato',
    nickname: ['MASKING', 'Masuki'],
    description:
      'Appears gruff but is passionate and caring. The daughter of the owner of the live house Galaxy. She started playing the drums to be like her drummer father. Although skilled, no other bands wanted her because when she gets excited, she will do difficult, improvised performances with no regard for the other members.',
    likes: ['Ramen', 'Vegetable curry'],
    dislikes: ['None'],
    hobbies: ['Drawing and reading manga', 'Baking cakes'],
    birthday_date: '05-12',
    profile_picture: '/images/characters/masking_profile.webp',
    image_color: '#EEBB44',
  },
  {
    id: 34,
    fullname: 'Reona Nyubara',
    nickname: ['PAREO', 'Reona'],
    description:
      "RAISE A SUILEN's keyboardist is obsessed with cuteness. A major Pastel＊Palettes fan, she always checks out their concerts and radio shows. Because CHU² is the one who found this new side of her, she deeply adores CHU². Sometimes, however, her adoration for CHU² makes her lose control of herself.",
    likes: ['Cabbage'],
    dislikes: ['Coriander', 'Raw onions'],
    hobbies: ['Idols'],
    birthday_date: '03-25',
    profile_picture: '/images/characters/pareo_profile.webp',
    image_color: '#FF99BB',
  },
  {
    id: 35,
    fullname: 'Chiyu Tamade',
    nickname: ['CHU²', 'Chiyu'],
    description:
      "RAISE A SUILEN's ace producer and writer and composer of the band's songs. Although she can be childish and selfish at times, her passion for music is first-rate. She used to have issues with regard to her world-class musician mother but overcame them with the help of the band. Loves jerky.",
    likes: ['Jerky', 'Sweet things (especially cakes made by Masuki)'],
    dislikes: ['Salad (she can eat a little bit with some dressings)'],
    hobbies: ['Appreciating music'],
    birthday_date: '12-07',
    profile_picture: '/images/characters/chuchu_profile.webp',
    image_color: '#00BBFF',
  },
  {
    id: 36,
    fullname: 'Tomori Takamatsu',
    nickname: 'Tomori',
    description:
      'The vocalist of MyGO!!!!!, who has a unique sense of perception. She likes collecting things she finds appealing, and often picks up stones or leaves she finds on the street. She is aware that her sense of perception is somewhat different from those around her, and worries about it, but at school she is loved as something of a mascot‑like presence.',
    likes: ['Konpeito', 'Seasoned seaweed', 'Furikake'],
    dislikes: ['Raw egg', 'Salmon roe', 'Cod roe'],
    hobbies: ['Collecting things she likes (stones, bandages, pretty leaves, etc.)'],
    birthday_date: '11-22',
    profile_picture: '/images/characters/tomori_profile.webp',
    image_color: '#77BBDD',
  },
  {
    id: 37,
    fullname: 'Anon Chihaya',
    nickname: 'Anon',
    description:
      "A girl who attracts people with her naturally bright personality and strong social skills. In middle school, she was very popular in her class and served as student council president. She was originally supposed to study abroad, but due to certain circumstances, she transferred into Haneoka Girls' Academy instead. With her strong drive and initiative, she became the key person in moving the band forward.",
    likes: ['Fruit sandwiches', 'Smoked salmon'],
    dislikes: ['Pickled plums', 'Sour food'],
    hobbies: ['Checking beauty-related videos'],
    birthday_date: '09-08',
    profile_picture: '/images/characters/anon_profile.webp',
    image_color: '#FF8899',
  },
  {
    id: 38,
    fullname: 'Rāna Kaname',
    nickname: 'Rāna',
    description:
      "A free-spirited girl who lives entirely by her instincts. She goes straight for anything she's interested in, but completely ignores things she's not, showing very strong likes and dislikes. She is drawn to people with a strong sense of ego and individuality. Raised surrounded by music, her performance skills are on par with professionals.",
    likes: ['Matcha', 'Soba', 'Yubeshi', 'Karukan'],
    dislikes: ['Garlic chives', 'Grated yam', 'Mint-flavored foods', 'Onions'],
    hobbies: ['Playing with cats'],
    birthday_date: '02-22',
    profile_picture: '/images/characters/rana_profile.webp',
    image_color: '#77DD77',
  },
  {
    id: 39,
    fullname: 'Soyo Nagasaki',
    nickname: 'Soyo',
    description:
      'The bassist of MyGO!!!!!, who has a gentle and laid-back aura. At school, she is a "motherly" figure who listens to everyone\'s problems and supports others when they are in trouble, earning the trust of those around her. However, she also shows a different side of herself to her band members that she does not reveal at school.',
    likes: ['Minestrone soup', 'Tea'],
    dislikes: ['Horumon'],
    hobbies: ['Aromatherapy'],
    birthday_date: '05-27',
    profile_picture: '/images/characters/soyo_profile.webp',
    image_color: '#FFDD88',
  },
  {
    id: 40,
    fullname: 'Taki Shiina',
    nickname: 'Taki',
    description:
      'A lone wolf who prefers being by herself. Due to her strong will and unfriendly demeanor, she often clashes with those around her, but once she acknowledges someone, she shows unwavering loyalty and sticks with them completely. She works part-time as a staff member at the live house "RiNG", but still seems to struggle with customer service.',
    likes: ['Almond tofu'],
    dislikes: ['Shiitake mushrooms', 'Shirataki noodles'],
    hobbies: ['Collecting panda merchandise', 'Singing karaoke alone'],
    birthday_date: '08-09',
    profile_picture: '/images/characters/taki_profile.webp',
    image_color: '#7777AA',
  },
  {
    id: 41,
    fullname: ['Uika Misumi', 'Hatsune Misumi'],
    nickname: ['Uika', 'Doloris', 'Hatsune'],
    description:
      "A 1st-year student at Hanasakigawa Girls' Academy. She is in the same class as Umiri and Taki. She also performs as part of the idol unit “sumimi.” She enjoys stargazing. She has known Sakiko since childhood and readily agreed to join the band when invited. In Ave Mujica, she is responsible for lyric writing.",
    likes: ['Pickled olives', 'Fish', 'Somen'],
    dislikes: ['TBA'],
    hobbies: ['Stargazing', 'Planetarium appreciation', 'Watching films', 'Reading'],
    birthday_date: '06-26',
    profile_picture: '/images/characters/uika_profile.webp',
    image_color: '#BB9955',
  },
  {
    id: 42,
    fullname: 'Mutsumi Wakaba',
    nickname: ['Mutsumi', 'Mortis'],
    description:
      "A 1st-year student at Tsukinomori Girls' Academy. She is in the same class as Soyo. She has difficulty expressing her emotions and is poor at communication, but she does have a considerate side in her own way. Her father is Wakaba, a popular comedian, and her mother is actress Minami Mori. She has also been childhood friends with Sakiko. She has played guitar since early childhood and is highly skilled.",
    likes: ['???'],
    dislikes: ['TBA'],
    hobbies: ['???'],
    birthday_date: '01-14',
    profile_picture: '/images/characters/mutsumi_profile.webp',
    image_color: '#779977',
  },
  {
    id: 43,
    fullname: 'Umiri Yahata',
    nickname: ['Umiri', 'Timoris'],
    description:
      "A 1st-year student at Hanasakigawa Girls' Academy. She is in the same class as Uika and Taki. Her bass skills are on a professional level, and she once juggled multiple bands as a support musician. In Ave Mujica, she handles behind-the-scenes work such as coordinating members' schedules.",
    likes: ['Fried noodles with a sunny-side-up egg'],
    dislikes: ['TBA'],
    hobbies: [
      'Music appreciation',
      'Customizing audio equipment',
      'Collecting vinyl records and silver jewellery',
    ],
    birthday_date: '04-07',
    profile_picture: '/images/characters/umiri_profile.webp',
    image_color: '#335566',
  },
  {
    id: 44,
    fullname: 'Nyamu Yūtenji',
    nickname: ['Nyamu', 'Amoris'],
    description:
      'A video creator known by the name “Nyamuchi.” While her roots are in beauty, she is currently expanding her creative scope by venturing into diverse new genres. An ambidextrous talent, she also draws attention with her captivating and flashy drumming style. Off-camera, she is a student at Geijutsu High School of Fine Arts, where she is honing her acting skills.',
    likes: ['Spicy things', 'Watermelon', 'Asian pear'],
    dislikes: ['TBA'],
    hobbies: ['Beauty shopping', 'Picking out gifts'],
    birthday_date: '06-01',
    profile_picture: '/images/characters/nyamu_profile.webp',
    image_color: '#AA4477',
  },
  {
    id: 45,
    fullname: 'Sakiko Togawa',
    nickname: ['Sakiko', 'Oblivionis'],
    description:
      "A first-year high school student at Haneoka Girls' Academy. As the daughter from the prestigious Togawa family, she speaks with refined, elegant manners. With the resolve to take responsibility for the lives of all the members, she formed Ave Mujica. She devotes herself wholeheartedly to preserving the world of Ave Mujica.",
    likes: ['Black Tea', 'Chocolate'],
    dislikes: ['TBA'],
    hobbies: ['Art appreciation', 'Reading'],
    birthday_date: '02-14',
    profile_picture: '/images/characters/sakiko_profile.webp',
    image_color: '#7799CC',
  },
  {
    id: 46,
    fullname: 'Arale Nakamachi',
    nickname: 'Arale',
    description:
      "A girl who loves singing and chatting. She's generally bright and energetic, but can sometimes get carried away or feel down—a bit of a whirlwind of emotions. Musically, she leads Mugendai MewType with her powerful, strong singing voice—a truly energetic and dynamic girl.",
    likes: ['Melon bun ice cream', 'Spicy foods'],
    dislikes: ['TBA'],
    hobbies: ['Manga', 'Anime'],
    birthday_date: '08-16',
    profile_picture: '/images/characters/arale_profile.webp',
    image_color: '#FFDD33',
  },
  {
    id: 47,
    fullname: 'Nonoka Miyanaga',
    nickname: 'Nonoka',
    description:
      "Mugendai MewType's carefree and lighthearted guitarist. A free-spirited, and fun-loving mood-maker loved by everyone. On stage, she draws the audience in with performances that show just how much she enjoys the music.",
    likes: ['White rice', 'Stew'],
    dislikes: ['TBA'],
    hobbies: ['Board games'],
    birthday_date: '04-17',
    profile_picture: '/images/characters/nonoka_profile.webp',
    image_color: '#FFAACC',
  },
  {
    id: 48,
    fullname: 'Ritsu Minetsuki',
    nickname: 'Ritsu',
    description:
      "A diligent, straight-A student. As the rhythm guitarist of Mugendai MewType, she calmly supports the band's sound. Perhaps because of her earnest nature, she occasionally surprises everyone with unexpected actions. Her appetite is seemingly endless—by far the biggest in the group.",
    likes: ['Sukiyaki', 'Ramen'],
    dislikes: ['TBA'],
    hobbies: ['Watching films'],
    birthday_date: '02-07',
    profile_picture: '/images/characters/ritsu_profile.webp',
    image_color: '#5588DD',
  },
  {
    id: 49,
    fullname: 'Miyako Fuji',
    nickname: 'Miyako',
    description:
      'An active manga artist and the keyboardist of Mugendai MewType. Though she may appear quiet at first glance, she supports the band with solid skill and an unwavering passion that never cuts corners. Balancing both her band activities and her work as a manga artist, she handles an extraordinary workload with remarkable discipline.',
    likes: ['Donuts', 'Sushi'],
    dislikes: ['TBA'],
    hobbies: ['Ikebana'],
    birthday_date: '19-09',
    profile_picture: '/images/characters/miyako_profile.webp',
    image_color: '#9977DD',
  },
  {
    id: 50,
    fullname: 'Yuno Sengoku',
    nickname: 'Yuno',
    description:
      "Mugendai MewType's laid-back DJ and manipulator. At the core of YMMT's music, she controls and supports the band's overall performance. A homebody who rarely goes outside, she comes across as cool and detached when interacting with others, but she actually has a warm and caring side deep down.",
    likes: ['White chocolate', 'Energy drinks'],
    dislikes: ['TBA'],
    hobbies: ['Video games'],
    birthday_date: '11-04',
    profile_picture: '/images/characters/yuno_profile.webp',
    image_color: '#FF6688',
  },
  {
    id: 51,
    fullname: 'Hotaru Shiomi',
    nickname: 'Hotaru',
    description:
      'A kind-hearted musical prodigy. Since childhood, she has achieved outstanding results in classical piano competitions, earning her the nickname "Angel of the Musical World." Pure and highly sensitive, she also has a somewhat naïve side.',
    likes: ['Egg Boro Cookies'],
    dislikes: ['TBA'],
    hobbies: ['Gardening'],
    birthday_date: '03-12',
    profile_picture: '/images/characters/hotaru_profile.webp',
    image_color: '#9AFF99',
  },
  {
    id: 52,
    fullname: 'Natsume Izawa',
    nickname: 'Natsume',
    description:
      "An overconfident composer. Extremely prideful, she tends to be confrontational and quick to assert dominance over anyone she doesn't deem worthy. She often commandeers the school rooftop, thrashing away on her guitar.",
    likes: ['Grab-and-go', 'Hard water'],
    dislikes: ['TBA'],
    hobbies: ['Vintage shop hopping'],
    birthday_date: '03-30',
    profile_picture: '/images/characters/natsume_profile.webp',
    image_color: '#FF4446',
  },
  {
    id: 53,
    fullname: 'Nagi Kotohira',
    nickname: 'Nagi',
    description:
      'A girl with a calm and composed presence. Her relaxed manner and refined way of speaking often make her seem more mature than her actual age. Apparently, there is a secret fan club of her at the all-girls school she attends.',
    likes: ['Lollipops'],
    dislikes: ['TBA'],
    hobbies: ['Reading', 'Watching movies'],
    birthday_date: '12-10',
    profile_picture: '/images/characters/nagi_profile.webp',
    image_color: '#5355FF',
  },
  {
    id: 54,
    fullname: 'Mahoro Hamasaki',
    nickname: 'Mahoro',
    description:
      'The one who keeps the band together. Friendly and easygoing, she has a natural way of getting along with everyone. She treasures the days spent with the band they formed together more than anyone else. She has two childhood friends.',
    likes: ['Pastries', 'Curry'],
    dislikes: ['TBA'],
    hobbies: ['Photography'],
    birthday_date: '07-16',
    profile_picture: '/images/characters/mahoro_profile.webp',
    image_color: '#76FFFF',
  },
  {
    id: 55,
    fullname: 'Houka Izumi',
    nickname: 'Houka',
    description:
      'A graceful and refined girl. Sociable and well-mannered, she\'s a popular presence in her class, with just a hint of playful charm. She has a strong fascination with overwhelming "talent."',
    likes: ['Japanese cuisine', 'French cuisine'],
    dislikes: ['TBA'],
    hobbies: ['Gourmet'],
    birthday_date: '10-24',
    profile_picture: '/images/characters/houka_profile.webp',
    image_color: '#EE9AEF',
  },
  {
    id: 56,
    fullname: 'Raika Suga',
    nickname: 'Raika',
    description:
      "Bright, honest, and energetic, though a bit rough around the edges. She's the type to act before she thinks. While she generally respects and supports others, once she makes up her mind, she can be quite stubborn.",
    likes: ['Freshly cooked rice', 'Hot pot', 'Yakiniku', 'Okonomiyaki', 'Other hot plate dishes'],
    dislikes: ['TBA'],
    hobbies: ['Watching baseball'],
    birthday_date: '07-28',
    profile_picture: '/images/characters/raika_profile.webp',
    image_color: '#FF7801',
  },
  {
    id: 57,
    fullname: 'Miku Mahashi',
    nickname: 'Miku',
    description:
      "Gentle and easy to get along with. Though she has a strong core and a grounded, practical way of thinking, she doesn't reveal her true feelings until she fully trusts someone. She doesn't pry too deeply into others, and prefers they do the same.",
    likes: ['Fruit tarts'],
    dislikes: ['TBA'],
    hobbies: ['???'],
    birthday_date: '10-04',
    profile_picture: '/images/characters/miku_profile.webp',
    image_color: '#23CCFF',
  },
  {
    id: 58,
    fullname: 'Yomogi Yakura',
    nickname: 'Yomogi',
    description:
      'Prone to stage fright and easily shaken, she struggles with interacting with others. She is currently withdrawn in her dorm and on a leave of absence from university. Deep down, she admires delinquent manga characters, and while she has plenty of "imaginary rehearsals," it never quite translates into real-life action.',
    likes: ['Soft senbei', 'Yokan', 'Spicy foods (she wants to like them)'],
    dislikes: ['TBA'],
    hobbies: ['An otaku of a certain delinquent manga'],
    birthday_date: '05-06',
    profile_picture: '/images/characters/yomogi_profile.webp',
    image_color: '#438789',
  },
  {
    id: 59,
    fullname: 'Chieri Umezato',
    nickname: 'Chieri',
    description:
      "A rebellious girl—willful, but somehow hard to hate. She craves attention, but isn't exactly quick on the uptake, so she messes up a lot. Still, she never gets discouraged, and she's very loud. Like really loud.",
    likes: ['Meat'],
    dislikes: ['TBA'],
    hobbies: ['???'],
    birthday_date: '04-02',
    profile_picture: '/images/characters/chieri_profile.webp',
    image_color: '#FE55AC',
  },
  {
    id: 60,
    fullname: 'Shizuku Shinomiya',
    nickname: 'Shizuku',
    description:
      'The mysterious youngest member. Despite her age, she carries an unusually calm presence and speaks in a refined, almost old-fashioned manner. Her values, way of thinking, and exceptional piano skills all give off the impression that she was not raised in an ordinary household.',
    likes: ['N/A'],
    dislikes: ['TBA'],
    hobbies: ['N/A'],
    birthday_date: '03-05',
    profile_picture: '/images/characters/shizuku_profile.webp',
    image_color: '#9A99FF',
  },
] satisfies CharacterData[];
